<title>Week 1 &mdash; Dowan (DECj)</title>
    <?php $this->layout = 'ccsdt'; ?>
    <meta http-equiv="refresh" content="240"><div id="title">
    <h2 id="sdc"><center>CCSDT#3 for DCSS v0.34</center></h2>
    <h2>Week 1 &mdash; Dowan (DECj)</h2></div><div id="content"><div id="times"><span class="label">Week of: </span>2026-05-15 (ends at start of 2026-05-22 00:00 UTC)</div><div id="combo"><span class="label">Character: </span>Deep Elf Conjurer</div>
<div id="bonus"><span class="label">Bonus 1: </span>Enter the bottom floor of the Orcish Mines before XL11.<br/>
<span class="label">Bonus 2: </span>Kill a Hell Lord unique. (Geryon does not count)</div>
<div id="gods"><span class="label">Gods: </span>Xom, Trog, Qazlal</div><br><pre>LEGEND<br>------<br>Green = Won<br>Red   = Died<br>Grey  = ongoing or did not finish<br>        before end of the week</right></pre><pre>SPECIAL NOTE<br>------------<br>None</pre><div class="card"><table><tr class="head">
    <th>Player</th>
    <th>Reach XL5</th>
    <th>Kill a Unique</th>
    <th>Worship a Valid God</th>
    <th>Reach XL10</th>
    <th>Branch Enter</th>
    <th>Branch End</th>
    <th>Champion a Valid God</th>
    <th><abbr title="Does not need to stay intact">Collect 1 Gem</abbr></th>
    <th>Collect 1 Rune</th>
    <th>Collect 2 Runes</th>
    <th>Collect 3 Runes</th>
    <th>Obtain Orb of Zot</th>
    <th>Win</th>
    <th>Bonus #1</th>
    <th>Bonus #2</th>
    <th>Week's Total (max=15)</th>
    </tr><tr class="won"><td class="name"><a href="https://archive.nemelex.cards/morgue//De02/morgue-De02-20260516-144755.txt">De02</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">15</td></tr>
<tr class="won"><td class="name"><a href="https://archive.nemelex.cards/morgue//Mneme/morgue-Mneme-20260521-100359.txt">Mneme</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">15</td></tr>
<tr class="won"><td class="name"><a href="http://underhound.eu/crawl/morgue/xeno23/morgue-xeno23-20260517-203812.txt">xeno23</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">15</td></tr>
<tr class="won"><td class="name"><a href="http://underhound.eu/crawl/morgue/Hasart/morgue-Hasart-20260516-115532.txt">Hasart</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="total">14</td></tr>
<tr class="won"><td class="name"><a href="https://data.crawlcosplay.org/morgue//PieDemon/morgue-PieDemon-20260520-000558.txt">PieDemon</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">13</td></tr>
<tr class="won"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/jt/morgue-jt-20260516-125022.txt">jt</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="total">13</td></tr>
<tr class="won"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//AutarchDCSS/morgue-AutarchDCSS-20260519-195119.txt">AutarchDCSS</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="total">13</td></tr>
<tr class="won"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/krsz/morgue-krsz-20260518-224719.txt">krsz</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="total">13</td></tr>
<tr class="won"><td class="name"><a href="https://crawl.project357.org/morgue/DraconiusTourney/morgue-DraconiusTourney-20260520-023016.txt">DraconiusTourney</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="total">13</td></tr>
<tr class="won"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/frus/morgue-frus-20260521-061230.txt">frus</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="total">13</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/TCC/morgue-TCC-20260517-201957.txt">TCC</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">12</td></tr>
<tr class="dead"><td class="name"><a href="https://archive.nemelex.cards/morgue//opking/morgue-opking-20260515-121612.txt">opking</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">12</td></tr>
<tr class="won"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/IjonTichy1/morgue-IjonTichy1-20260515-224536.txt">IjonTichy1</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="total">11</td></tr>
<tr class="won"><td class="name"><a href="https://crawl.project357.org/morgue/wagawaga/morgue-wagawaga-20260520-183359.txt">wagawaga</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="total">11</td></tr>
<tr class="dead"><td class="name"><a href="https://data.crawlcosplay.org/morgue//RoGGa/morgue-RoGGa-20260516-211305.txt">RoGGa</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">11</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//erikjake/morgue-erikjake-20260516-034107.txt">erikjake</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">11</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/ThePixelVillain/morgue-ThePixelVillain-20260521-204627.txt">ThePixelVillain</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">10</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/stinkchinker/morgue-stinkchinker-20260515-173855.txt">stinkchinker</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">10</td></tr>
<tr class="dead"><td class="name"><a href="https://data.crawlcosplay.org/morgue//InabaYap/morgue-InabaYap-20260516-153056.txt">InabaYap</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">10</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/vanbol/morgue-vanbol-20260517-170638.txt">vanbol</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">10</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/dizzi/morgue-dizzi-20260517-232347.txt">dizzi</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">10</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/BlueFrogs/morgue-BlueFrogs-20260520-081227.txt">BlueFrogs</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">9</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/predelnik/morgue-predelnik-20260516-152012.txt">predelnik</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">9</td></tr>
<tr class="dead"><td class="name"><a href="https://data.crawlcosplay.org/morgue//quinnr/morgue-quinnr-20260516-190911.txt">quinnr</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">9</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/petercordia/morgue-petercordia-20260516-184244.txt">petercordia</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">8</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//particleface/morgue-particleface-20260515-143824.txt">particleface</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">8</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/agentchuck/morgue-agentchuck-20260517-125208.txt">agentchuck</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">8</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/Wizard1ke/morgue-Wizard1ke-20260521-093706.txt">Wizard1ke</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">8</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//croikle/morgue-croikle-20260517-172351.txt">croikle</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">8</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//community/morgue-community-20260516-140019.txt">community</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">8</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//SlowGraham/morgue-SlowGraham-20260519-173809.txt">SlowGraham</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">8</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/TomBombadil/morgue-TomBombadil-20260515-133531.txt">TomBombadil</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">8</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//cron3/morgue-cron3-20260518-130432.txt">cron3</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">7</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Tungsten/morgue-Tungsten-20260520-220736.txt">Tungsten</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">7</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Kergan/morgue-Kergan-20260515-184229.txt">Kergan</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">7</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Colgate/morgue-Colgate-20260515-205833.txt">Colgate</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">6</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/ventricule/morgue-ventricule-20260517-135551.txt">ventricule</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">6</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//Galadan/morgue-Galadan-20260515-153158.txt">Galadan</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">6</td></tr>
<tr class="dead"><td class="name"><a href="https://data.crawlcosplay.org/morgue//Blyxx/morgue-Blyxx-20260515-060727.txt">Blyxx</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">5</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/LordBelias/morgue-LordBelias-20260517-190227.txt">LordBelias</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">5</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/mobilemanners/morgue-mobilemanners-20260516-133138.txt">mobilemanners</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">5</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.roguelikes.gg/morgue//Jaredude/morgue-Jaredude-20260516-051526.txt">Jaredude</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">5</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/rago/morgue-rago-20260515-160823.txt">rago</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">5</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/justinlove/morgue-justinlove-20260517-184506.txt">justinlove</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">5</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/Strat/morgue-Strat-20260515-141552.txt">Strat</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">5</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Nonny/morgue-Nonny-20260515-024859.txt">Nonny</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//CrazyBamboolord/morgue-CrazyBamboolord-20260515-134030.txt">CrazyBamboolord</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="https://archive.nemelex.cards/morgue//vayu/morgue-vayu-20260515-023352.txt">vayu</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/BadBadger/morgue-BadBadger-20260515-215831.txt">BadBadger</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="https://archive.nemelex.cards/morgue//sekai/morgue-sekai-20260516-042647.txt">sekai</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//jaccarmac/morgue-jaccarmac-20260519-212601.txt">jaccarmac</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/D1NKY/morgue-D1NKY-20260520-170955.txt">D1NKY</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//Patrick2011b/morgue-Patrick2011b-20260515-012009.txt">Patrick2011b</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/aj12037/morgue-aj12037-20260515-073451.txt">aj12037</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="https://archive.nemelex.cards/morgue//icedessert/morgue-icedessert-20260521-111620.txt">icedessert</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.roguelikes.gg/morgue//nojaa/morgue-nojaa-20260517-214442.txt">nojaa</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/drwombats/morgue-drwombats-20260519-002826.txt">drwombats</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/here/morgue-here-20260516-141624.txt">here</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/eccles/morgue-eccles-20260519-222405.txt">eccles</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="https://archive.nemelex.cards/morgue//Tanach/morgue-Tanach-20260518-033141.txt">Tanach</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/Migumi/morgue-Migumi-20260517-102347.txt">Migumi</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Shym/morgue-Shym-20260515-062539.txt">Shym</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="https://archive.nemelex.cards/morgue//Mumonspawn/morgue-Mumonspawn-20260518-082048.txt">Mumonspawn</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="https://archive.nemelex.cards/morgue//vayu1/morgue-vayu1-20260521-103747.txt">vayu1</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/flt/morgue-flt-20260519-074204.txt">flt</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//TheMeInTeam/morgue-TheMeInTeam-20260519-161904.txt">TheMeInTeam</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/XavTav/morgue-XavTav-20260521-173408.txt">XavTav</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/prygans/morgue-prygans-20260515-101555.txt">prygans</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Nebesus/morgue-Nebesus-20260517-233203.txt">Nebesus</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/achylon/morgue-achylon-20260520-173502.txt">achylon</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/Leibowitz/morgue-Leibowitz-20260518-203219.txt">Leibowitz</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/thelochok/morgue-thelochok-20260516-060118.txt">thelochok</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/Pythonsnek/morgue-Pythonsnek-20260520-144653.txt">pythonsnek</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/emiel/morgue-emiel-20260521-200405.txt">emiel</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/lontrex/morgue-lontrex-20260519-040113.txt">lontrex</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//attentat/morgue-attentat-20260516-005047.txt">attentat</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/MisterOstroum/morgue-MisterOstroum-20260517-052658.txt">MisterOstroum</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Astinus/morgue-Astinus-20260518-021642.txt">Astinus</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Larett/morgue-Larett-20260518-190319.txt">Larett</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/tmoiynmwg/morgue-tmoiynmwg-20260516-023324.txt">tmoiynmwg</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/goupaloupa/morgue-goupaloupa-20260521-124641.txt">goupaloupa</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Midpoint/morgue-Midpoint-20260515-151410.txt">Midpoint</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/Loefaen/morgue-Loefaen-20260515-152900.txt">Loefaen</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/Th3BaraKing/morgue-Th3BaraKing-20260520-010446.txt">Th3BaraKing</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/brinewave/morgue-brinewave-20260518-064950.txt">brinewave</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Voda/morgue-Voda-20260517-233539.txt">Voda</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/aimeelou/morgue-aimeelou-20260515-221418.txt">aimeelou</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/riffraff/morgue-riffraff-20260518-085458.txt">riffraff</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/ElricMelnibone/morgue-ElricMelnibone-20260515-084609.txt">ElricMelnibone</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="https://data.crawlcosplay.org/morgue//RoGGaTestCCO/morgue-RoGGaTestCCO-20260518-145644.txt">RoGGaTestCCO</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Mene/morgue-Mene-20260515-163429.txt">Mene</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/elguitar/morgue-elguitar-20260515-100505.txt">elguitar</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/Endy73/morgue-Endy73-20260516-202310.txt">Endy73</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Arcadio/morgue-Arcadio-20260518-174422.txt">Arcadio</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/N1ckwad/morgue-N1ckwad-20260518-051501.txt">N1ckwad</a></td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/haldagan/morgue-haldagan-20260515-124327.txt">haldagan</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="alive"><td class="name">Platt</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Barata/morgue-Barata-20260515-145821.txt">Barata</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://archive.nemelex.cards/morgue//nodap/morgue-nodap-20260517-051836.txt">nodap</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="alive"><td class="name">Fougere</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="none"><td class="name">Name63</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Pascal76</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">James</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">mihai</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">kuniqs</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">RichitheSlayer</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">cornishon</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Jannitor</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Salticid</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">sneaky</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">baljet</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">AmeliaG</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">browni3141</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Snarg</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Myro</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">THILQ</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">DocSulfur</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Wolffangen</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Haldmier</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Damoeire</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Quoth</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Archion</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">TooFastSpriggan</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">ASCIIPhilia</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Magatonman</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">yakattack</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Abbadon</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Hungry0364</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Caterwaul</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">badboneX</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">adinsx</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">anonymouscript</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">kae</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">PizzaParty</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Klimbambiesel</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">potion</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">authentic</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">diiiiiane</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">K8SM8S</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Azareth</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Doot</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">ThatCXCTrollOstroum</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">eachpiece</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Swimfan</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">mive</td>
                <td colspan="15"></td><td class="total">0</td></tr></table></div></div>
    <div id="bottomtext"><span class="menu">CCSDT for v0.34</a> : </span><span class="menu"><img src="/img/animated-arrow.gif" width="40" height="10"></span><span class="menu"><a href="index.html">Overview</a> - </span><span class="menu"><a href="rules.html">Details</a> - </span><span class="menu"><a href="standings.html">Standings</a></span><span class="menuspacer"></span><span class="menu">Week 1 - </span><span class="menu"><a href="2.html">Week 2</a> - </span><span class="menu"><a href="3.html">Week 3</a> - </span><span class="menu"><a href="4.html">Week 4</a> - </span><span class="menu">Week 5 - </span><span id="updated"><span class="label">Updates every 10 mins. Last Update: </span>2026-06-05 10:09 UTC</span></div>