<title>Week 1 &mdash; Dowan (DECj)</title>
    <?php $this->layout = 'ccsdt'; ?>
    <meta http-equiv="refresh" content="240"><div id="title">
    <h2 id="sdc"><center>CCSDT#3 for DCSS v0.34</center></h2>
    <h2>Week 1 &mdash; Dowan (DECj)</h2></div><div id="content"><div id="times"><span class="label">Week of: </span>2026-05-15 (ends at start of 2026-05-22 00:00 UTC)</div><div id="combo"><span class="label">Character: </span>Deep Elf Conjurer</div>
<div id="bonus"><span class="label">Bonus 1: </span>Enter the bottom floor of the Orcish Mines before XL11.<br/>
<span class="label">Bonus 2: </span>Kill a Hell Lord unique. (Geryon does not count)</div>
<div id="gods"><span class="label">Gods: </span>Xom, Trog, Qazlal</div><br><pre>LEGEND<br>------<br>Green = Won<br>Red   = Died<br>Grey  = ongoing or did not finish before end of the week</right></pre><div class="card"><table><tr class="head">
    <th>Player</th>
    <th>Reach XL5</th>
    <th>Kill a Unique</th>
    <th>Worship a Valid God</th>
    <th>Reach XL10</th>
    <th>Branch Enter</th>
    <th>Branch End</th>
    <th>Champion a Valid God</th>
    <th><abbr title="Does not need to stay intact">Collect 1 Gem</abbr></th>
    <th>Collect 1 Rune</th>
    <th>Collect 2 Runes</th>
    <th>Collect 3 Runes</th>
    <th>Obtain Orb of Zot</th>
    <th>Win</th>
    <th>Bonus #1</th>
    <th>Bonus #2</th>
    <th>Week's Total (max=15)</th>
    </tr><tr class="won"><td class="name"><a href="https://archive.nemelex.cards/morgue//De02/morgue-De02-20260516-144755.txt">De02</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">15</td></tr>
<tr class="won"><td class="name"><a href="http://underhound.eu/crawl/morgue/xeno23/morgue-xeno23-20260517-203812.txt">xeno23</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">15</td></tr>
<tr class="won"><td class="name"><a href="http://underhound.eu/crawl/morgue/Hasart/morgue-Hasart-20260516-115532.txt">Hasart</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="total">14</td></tr>
<tr class="won"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/jt/morgue-jt-20260516-125022.txt">jt</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="total">13</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/TCC/morgue-TCC-20260517-201957.txt">TCC</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">12</td></tr>
<tr class="dead"><td class="name"><a href="https://archive.nemelex.cards/morgue//opking/morgue-opking-20260515-121612.txt">opking</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">12</td></tr>
<tr class="won"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/IjonTichy1/morgue-IjonTichy1-20260515-224536.txt">IjonTichy1</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="total">11</td></tr>
<tr class="dead"><td class="name"><a href="https://data.crawlcosplay.org/morgue//RoGGa/morgue-RoGGa-20260516-211305.txt">RoGGa</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">11</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//erikjake/morgue-erikjake-20260516-034107.txt">erikjake</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">11</td></tr>
<tr class="alive"><td class="name">krsz</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">11</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/stinkchinker/morgue-stinkchinker-20260515-173855.txt">stinkchinker</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">10</td></tr>
<tr class="dead"><td class="name"><a href="https://data.crawlcosplay.org/morgue//InabaYap/morgue-InabaYap-20260516-153056.txt">InabaYap</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">10</td></tr>
<tr class="alive"><td class="name">PieDemon</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">10</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/vanbol/morgue-vanbol-20260517-170638.txt">vanbol</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">10</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/predelnik/morgue-predelnik-20260516-152012.txt">predelnik</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">9</td></tr>
<tr class="dead"><td class="name"><a href="https://data.crawlcosplay.org/morgue//quinnr/morgue-quinnr-20260516-190911.txt">quinnr</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">9</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/petercordia/morgue-petercordia-20260516-184244.txt">petercordia</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">8</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//particleface/morgue-particleface-20260515-143824.txt">particleface</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">8</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/agentchuck/morgue-agentchuck-20260517-125208.txt">agentchuck</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">8</td></tr>
<tr class="alive"><td class="name">BlueFrogs</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">8</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//croikle/morgue-croikle-20260517-172351.txt">croikle</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">8</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//community/morgue-community-20260516-140019.txt">community</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">8</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/TomBombadil/morgue-TomBombadil-20260515-133531.txt">TomBombadil</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">8</td></tr>
<tr class="alive"><td class="name">DraconiusTourney</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">8</td></tr>
<tr class="alive"><td class="name">ThePixelVillain</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">7</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Kergan/morgue-Kergan-20260515-184229.txt">Kergan</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">7</td></tr>
<tr class="alive"><td class="name">cron3</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">7</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Colgate/morgue-Colgate-20260515-205833.txt">Colgate</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">6</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/ventricule/morgue-ventricule-20260517-135551.txt">ventricule</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">6</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//Galadan/morgue-Galadan-20260515-153158.txt">Galadan</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">6</td></tr>
<tr class="dead"><td class="name"><a href="https://data.crawlcosplay.org/morgue//Blyxx/morgue-Blyxx-20260515-060727.txt">Blyxx</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">5</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/LordBelias/morgue-LordBelias-20260517-190227.txt">LordBelias</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">5</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/mobilemanners/morgue-mobilemanners-20260516-133138.txt">mobilemanners</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">5</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.roguelikes.gg/morgue//Jaredude/morgue-Jaredude-20260516-051526.txt">Jaredude</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">5</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/rago/morgue-rago-20260515-160823.txt">rago</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">5</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/justinlove/morgue-justinlove-20260517-184506.txt">justinlove</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">5</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/Strat/morgue-Strat-20260515-141552.txt">Strat</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">5</td></tr>
<tr class="alive"><td class="name">Tungsten</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">5</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Nonny/morgue-Nonny-20260515-024859.txt">Nonny</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//CrazyBamboolord/morgue-CrazyBamboolord-20260515-134030.txt">CrazyBamboolord</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="https://archive.nemelex.cards/morgue//vayu/morgue-vayu-20260515-023352.txt">vayu</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/BadBadger/morgue-BadBadger-20260515-215831.txt">BadBadger</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="https://archive.nemelex.cards/morgue//sekai/morgue-sekai-20260516-042647.txt">sekai</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//Patrick2011b/morgue-Patrick2011b-20260515-012009.txt">Patrick2011b</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/aj12037/morgue-aj12037-20260515-073451.txt">aj12037</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/here/morgue-here-20260516-141624.txt">here</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/Migumi/morgue-Migumi-20260517-102347.txt">Migumi</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Shym/morgue-Shym-20260515-062539.txt">Shym</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/prygans/morgue-prygans-20260515-101555.txt">prygans</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/thelochok/morgue-thelochok-20260516-060118.txt">thelochok</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="alive"><td class="name">XavTav</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//attentat/morgue-attentat-20260516-005047.txt">attentat</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/MisterOstroum/morgue-MisterOstroum-20260517-052658.txt">MisterOstroum</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/tmoiynmwg/morgue-tmoiynmwg-20260516-023324.txt">tmoiynmwg</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Midpoint/morgue-Midpoint-20260515-151410.txt">Midpoint</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/Loefaen/morgue-Loefaen-20260515-152900.txt">Loefaen</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/aimeelou/morgue-aimeelou-20260515-221418.txt">aimeelou</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/ElricMelnibone/morgue-ElricMelnibone-20260515-084609.txt">ElricMelnibone</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="alive"><td class="name">Astinus</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="alive"><td class="name">nojaa</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Mene/morgue-Mene-20260515-163429.txt">Mene</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/elguitar/morgue-elguitar-20260515-100505.txt">elguitar</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/Endy73/morgue-Endy73-20260516-202310.txt">Endy73</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="alive"><td class="name">Platt</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Barata/morgue-Barata-20260515-145821.txt">Barata</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Larett/morgue-Larett-20260517-203936.txt">Larett</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="none"><td class="name">N1ckwad</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Pascal76</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">kuniqs</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Jannitor</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Salticid</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">baljet</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">TheMeInTeam</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Myro</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">THILQ</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Fougere</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Wolffangen</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Damoeire</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Quoth</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Archion</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">TooFastSpriggan</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">ASCIIPhilia</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Magatonman</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">yakattack</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Hungry0364</td>
                <td colspan="15"></td><td class="total">0</td></tr><tr class="none"><td class="name">Caterwaul</td>
                <td colspan="15"></td><td class="total">0</td></tr></table></div></div>
    <div id="bottomtext"><span class="menu">CCSDT for v0.34</a> : </span><span class="menu"><img src="/img/animated-arrow.gif" width="40" height="10"></span><span class="menu"><a href="index.html">Overview</a> - </span><span class="menu"><a href="rules.html">Details</a> - </span><span class="menu"><a href="standings.html">Standings</a></span><span class="menuspacer"></span><span class="menu">Week 1 - </span><span class="menu">Week 2 - </span><span class="menu">Week 3 - </span><span class="menu">Week 4 - </span><span class="menu">Week 5 - </span><span id="updated"><span class="label">Updates every 10 mins. Last Update: </span>2026-05-17 20:50 UTC</span></div>