<title>Week 2 &mdash; GnSu</title>
    <?php $this->layout = 'ccsdt'; ?>
    <meta http-equiv="refresh" content="240"><div id="title">
    <h2 id="sdc"><center>CCSDT#2 for DCSS v0.33</center></h2>
    <h2>Week 2 &mdash; GnSu</h2></div><div id="content"><div id="times"><span class="label">Week of 2025-09-12</span></div><div id="combo"><span class="label">Character: </span>Gnoll Summoner</div>
<div id="bonus"><span class="label">Bonus 1: </span>Reach the end of the Depths before entering a rune branch (excluding getting banished to the Abyss).<br/>
<span class="label">Bonus 2: </span>Get a rune from Hell or Pan before entering any other rune branch (excluding the Abyss).</div>
<div id="gods"><span class="label">Gods: </span>Lugonu, Dithmenos, The Shining One</div><br><pre>LEGEND<br>------<br>Green = Won<br>Red   = Died<br>Grey  = ongoing or did not finish</right></pre><div class="card"><table><tr class="head">
    <th>Player</th>
    <th>Unique Kill</th>
    <th>Branch Enter</th>
    <th>Branch End</th>
    <th>Champion God</th>
    <th>Collect a Rune</th>
    <th>Collect 3 Runes</th>
    <th>Obtain the Orb</th>
    <th>Win</th>
    <th>Bonus 1</th>
    <th>Bonus 2</th>
    <th>Total</th>
    </tr><tr class="won"><td class="name"><a href="https://cbro.berotato.org/morgue//Zeldest/morgue-Zeldest-20250912-193854.txt">Zeldest</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">10</td></tr>
<tr class="won"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/InabaYap/morgue-InabaYap-20250916-001357.txt">InabaYap</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">10</td></tr>
<tr class="won"><td class="name"><a href="https://cbro.berotato.org/morgue//particleface/morgue-particleface-20250916-163435.txt">particleface</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">10</td></tr>
<tr class="won"><td class="name"><a href="https://cbro.berotato.org/morgue//TheMeInTeam/morgue-TheMeInTeam-20250913-050400.txt">TheMeInTeam</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">10</td></tr>
<tr class="won"><td class="name"><a href="https://crawl.project357.org/morgue/Draconius/morgue-Draconius-20250913-113845.txt">Draconius</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">10</td></tr>
<tr class="won"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/ousd/morgue-ousd-20250917-060836.txt">ousd</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">10</td></tr>
<tr class="won"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//planckenstein/morgue-planckenstein-20250917-012738.txt">planckenstein</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">10</td></tr>
<tr class="won"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/agentchuck/morgue-agentchuck-20250915-204217.txt">agentchuck</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">10</td></tr>
<tr class="won"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/TCC/morgue-TCC-20250918-165735.txt">TCC</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">10</td></tr>
<tr class="won"><td class="name"><a href="http://underhound.eu/crawl/morgue/TomBombadil/morgue-TomBombadil-20250912-201119.txt">TomBombadil</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">10</td></tr>
<tr class="won"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//demonstrator/morgue-demonstrator-20250914-113123.txt">demonstrator</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">10</td></tr>
<tr class="won"><td class="name"><a href="https://cbro.berotato.org/morgue//RoGGa/morgue-RoGGa-20250913-133711.txt">RoGGa</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="total">9</td></tr>
<tr class="won"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/krsz/morgue-krsz-20250914-071317.txt">krsz</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="total">8</td></tr>
<tr class="won"><td class="name"><a href="https://cbro.berotato.org/morgue//ContrarianOrange/morgue-ContrarianOrange-20250915-045141.txt">ContrarianOrange</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="total">8</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Dwargi/morgue-Dwargi-20250914-172242.txt">Dwargi</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="total">7</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/jt/morgue-jt-20250912-214648.txt">jt</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">6</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/IjonTichy1/morgue-IjonTichy1-20250912-112200.txt">IjonTichy1</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">6</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//PieDemon/morgue-PieDemon-20250912-170555.txt">PieDemon</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">6</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//erikjake/morgue-erikjake-20250914-024917.txt">erikjake</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">5</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//kkplay/morgue-kkplay-20250915-190223.txt">kkplay</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">5</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Strat/morgue-Strat-20250913-121832.txt">Strat</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">5</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//Hsik/morgue-Hsik-20250913-140343.txt">Hsik</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">5</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Platt/morgue-Platt-20250917-211934.txt">Platt</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">5</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/drwombats/morgue-drwombats-20250916-234439.txt">drwombats</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/mobilemanners/morgue-mobilemanners-20250914-133334.txt">mobilemanners</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/Jannitor/morgue-Jannitor-20250917-122614.txt">Jannitor</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Astinus/morgue-Astinus-20250914-043527.txt">Astinus</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/SuperSimple/morgue-SuperSimple-20250912-221159.txt">SuperSimple</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//community/morgue-community-20250913-191901.txt">community</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/justinlove/morgue-justinlove-20250914-223228.txt">justinlove</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/happinesssam/morgue-happinesssam-20250912-143236.txt">happinesssam</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/dreamdao/morgue-dreamdao-20250916-094349.txt">dreamdao</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Larett/morgue-Larett-20250913-101130.txt">Larett</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="alive"><td class="name">Blyxx</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Arcadio/morgue-Arcadio-20250912-154112.txt">Arcadio</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/tish/morgue-tish-20250912-110157.txt">tish</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//abclol0070/morgue-abclol0070-20250918-225620.txt">abclol0070</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//EugeneJudo/morgue-EugeneJudo-20250914-223527.txt">EugeneJudo</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="alive"><td class="name">K8SM8S</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="alive"><td class="name">LadyLuck</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//SlowGraham/morgue-SlowGraham-20250912-134438.txt">SlowGraham</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/AshKetchup/morgue-AshKetchup-20250913-205430.txt">AshKetchup</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/QuizMaster/morgue-QuizMaster-20250913-051547.txt">QuizMaster</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/Endy73/morgue-Endy73-20250914-150755.txt">Endy73</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/Spatula/morgue-Spatula-20250914-063130.txt">Spatula</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/PidgeonPower/morgue-PidgeonPower-20250916-221111.txt">PidgeonPower</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/nojaa/morgue-nojaa-20250916-162001.txt">nojaa</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//quinnr/morgue-quinnr-20250913-223249.txt">quinnr</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/Colgate/morgue-Colgate-20250912-170110.txt">Colgate</a></td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Disease/morgue-Disease-20250912-103438.txt">Disease</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Fougere/morgue-Fougere-20250918-174042.txt">Fougere</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/LottaHair/morgue-LottaHair-20250912-085546.txt">LottaHair</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//JolietJake/morgue-JolietJake-20250913-041418.txt">JolietJake</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/SpideyBoy/morgue-SpideyBoy-20250916-211009.txt">SpideyBoy</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/kickassninja/morgue-kickassninja-20250913-195556.txt">kickassninja</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/brinewave/morgue-brinewave-20250913-073236.txt">brinewave</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Gobbopathe/morgue-Gobbopathe-20250914-140633.txt">Gobbopathe</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/Mariano/morgue-Mariano-20250918-201756.txt">Mariano</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Snarg/morgue-Snarg-20250915-030643.txt">Snarg</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/CallieX/morgue-CallieX-20250913-042910.txt">CallieX</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/Abbadon/morgue-Abbadon-20250912-050852.txt">Abbadon</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//jaccarmac/morgue-jaccarmac-20250915-054855.txt">jaccarmac</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Esekla/morgue-Esekla-20250912-035801.txt">Esekla</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/Masnef/morgue-Masnef-20250912-192328.txt">Masnef</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Procrustes/morgue-Procrustes-20250912-141900.txt">Procrustes</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Hans/morgue-Hans-20250912-215826.txt">Hans</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="none"><td class="name">Pigkeeper</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Bronksi</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Syis</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">kuniqs</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">GameOver</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">ereinion</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">mdonais</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">zewo</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">TheBenjamin</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">tmt</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">BeansWater</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">AquaGlass</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">lontrex</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Aka8171</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">goupaloupa</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Archion</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">ASCIIPhilia</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">DWEMPhilia</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Caterwaul</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">yakattack</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">enarc13</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">ElricMelnibone</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">cpf86</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Scalebane</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">tyria</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Booper</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">CoolPlay</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Notte</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Vivy</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">playerghost</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">person50605</td>
                <td colspan="10"></td><td class="total">0</td></tr></table></div></div>
    <div id="bottomtext"><span class="menu"><a href="index.html">Overview</a> - </span><span class="menu"><a href="../about_ccsdt.html">Details</a> - </span><span class="menu"><a href="standings.html">Standings</a></span><span class="menuspacer"></span><span class="menu"><a href="1.html">Week 1</a> - </span><span class="menu">Week 2 - </span><span class="menu"><a href="3.html">Week 3</a> - </span><span class="menu">Week 4 - </span><span class="menu">Week 5 - </span><span id="updated"><span class="label">Updates every 10 mins. Last Update: </span>2025-09-25 23:52 UTC</span></div>