<title>Week 4 &mdash; ReNe</title>
    <?php $this->layout = 'ccsdt'; ?>
    <meta http-equiv="refresh" content="240"><div id="title">
    <h2 id="sdc"><center>CCSDT#2 for DCSS v0.33</center></h2>
    <h2>Week 4 &mdash; ReNe</h2></div><div id="content"><div id="times"><span class="label">Week of 2025-09-26</span></div><div id="combo"><span class="label">Character: </span>Revenant Necromancer</div>
<div id="bonus"><span class="label">Bonus 1: </span>Collect a rune before entering Lair.<br/>
<span class="label">Bonus 2: </span>Get a rune from Hell before entering any other rune branch (excluding the Abyss).</div>
<div id="gods"><span class="label">Gods: </span>Ru, Cheibriados, Kikubaaqudgha</div><br><pre>LEGEND<br>------<br>Green = Won<br>Red   = Died<br>Grey  = ongoing or did not finish</right></pre><div class="card"><table><tr class="head">
    <th>Player</th>
    <th>Unique Kill</th>
    <th>Branch Enter</th>
    <th>Branch End</th>
    <th>Champion God</th>
    <th>Collect a Rune</th>
    <th>Collect 3 Runes</th>
    <th>Obtain the Orb</th>
    <th>Win</th>
    <th>Bonus 1</th>
    <th>Bonus 2</th>
    <th>Total</th>
    </tr><tr class="won"><td class="name"><a href="http://underhound.eu/crawl/morgue/kuniqs/morgue-kuniqs-20250926-225742.txt">kuniqs</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">10</td></tr>
<tr class="won"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/agentchuck/morgue-agentchuck-20250930-175521.txt">agentchuck</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="total">9</td></tr>
<tr class="won"><td class="name"><a href="https://cbro.berotato.org/morgue//PieDemon/morgue-PieDemon-20250927-195003.txt">PieDemon</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="total">9</td></tr>
<tr class="won"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//planckenstein/morgue-planckenstein-20250930-193542.txt">planckenstein</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="total">9</td></tr>
<tr class="won"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/ousd/morgue-ousd-20251002-085855.txt">ousd</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="total">8</td></tr>
<tr class="won"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/TCC/morgue-TCC-20250927-162552.txt">TCC</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="total">8</td></tr>
<tr class="won"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/krsz/morgue-krsz-20250930-232040.txt">krsz</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="total">8</td></tr>
<tr class="won"><td class="name"><a href="http://underhound.eu/crawl/morgue/TomBombadil/morgue-TomBombadil-20250929-202845.txt">TomBombadil</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="total">8</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Colgate/morgue-Colgate-20251002-174231.txt">Colgate</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">6</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/jt/morgue-jt-20250927-184440.txt">jt</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">6</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/happinesssam/morgue-happinesssam-20250929-130925.txt">happinesssam</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/tish/morgue-tish-20250928-114137.txt">tish</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//ContrarianOrange/morgue-ContrarianOrange-20250927-035653.txt">ContrarianOrange</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//particleface/morgue-particleface-20251001-150101.txt">particleface</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//playerghost/morgue-playerghost-20250927-054140.txt">playerghost</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//AquaGlass/morgue-AquaGlass-20250928-134557.txt">AquaGlass</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/Draconius/morgue-Draconius-20250927-010905.txt">Draconius</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//TheMeInTeam/morgue-TheMeInTeam-20250926-015342.txt">TheMeInTeam</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Snarg/morgue-Snarg-20251003-184717.txt">Snarg</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//SlowGraham/morgue-SlowGraham-20250926-151006.txt">SlowGraham</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Arcadio/morgue-Arcadio-20250926-090206.txt">Arcadio</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Hans/morgue-Hans-20250926-230850.txt">Hans</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Esekla/morgue-Esekla-20250928-012622.txt">Esekla</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Procrustes/morgue-Procrustes-20250926-024441.txt">Procrustes</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Dwargi/morgue-Dwargi-20250927-120207.txt">Dwargi</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/IjonTichy1/morgue-IjonTichy1-20250926-085422.txt">IjonTichy1</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Gobbopathe/morgue-Gobbopathe-20250927-155657.txt">Gobbopathe</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/Abbadon/morgue-Abbadon-20250927-114555.txt">Abbadon</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Jannitor/morgue-Jannitor-20250926-150157.txt">Jannitor</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//community/morgue-community-20250926-172101.txt">community</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Larett/morgue-Larett-20250926-170845.txt">Larett</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Platt/morgue-Platt-20250928-143424.txt">Platt</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/nojaa/morgue-nojaa-20250926-113126.txt">nojaa</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//goupaloupa/morgue-goupaloupa-20251002-174734.txt">goupaloupa</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/lontrex/morgue-lontrex-20251001-150808.txt">lontrex</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//RoGGa/morgue-RoGGa-20250926-111952.txt">RoGGa</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/LadyLuck/morgue-LadyLuck-20250928-062506.txt">LadyLuck</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="alive"><td class="name">kkplay</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/justinlove/morgue-justinlove-20250928-000302.txt">justinlove</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/brinewave/morgue-brinewave-20250926-063844.txt">brinewave</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//quinnr/morgue-quinnr-20250927-205502.txt">quinnr</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/dreamdao/morgue-dreamdao-20251002-153229.txt">dreamdao</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//abclol0070/morgue-abclol0070-20250926-191124.txt">abclol0070</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://data.crawlcosplay.org/morgue//Pigkeeper/morgue-Pigkeeper-20250927-185234.txt">Pigkeeper</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://data.crawlcosplay.org/morgue//Blyxx/morgue-Blyxx-20250926-201720.txt">Blyxx</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Masnef/morgue-Masnef-20250927-121307.txt">Masnef</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//Hsik/morgue-Hsik-20250926-024851.txt">Hsik</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/drwombats/morgue-drwombats-20250926-073418.txt">drwombats</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/mobilemanners/morgue-mobilemanners-20250926-160624.txt">mobilemanners</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//jaccarmac/morgue-jaccarmac-20250926-054328.txt">jaccarmac</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Zeldest/morgue-Zeldest-20250927-124230.txt">Zeldest</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="none"><td class="name">demonstrator</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Bronksi</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Syis</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">GameOver</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">ereinion</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">erikjake</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Strat</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">JolietJake</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">mdonais</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">zewo</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Astinus</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">TheBenjamin</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">tmt</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">BeansWater</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">MrsPlatt</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">dakkaduck</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">DevastatorOne</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Endy73</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Fougere</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">InabaYap</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Aka8171</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Archion</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">EugeneJudo</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">ASCIIPhilia</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">DWEMPhilia</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Caterwaul</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">yakattack</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">enarc13</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">ElricMelnibone</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">kickassninja</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">cpf86</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Mariano</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">QuizMaster</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Scalebane</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">tyria</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Booper</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">K8SM8S</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Disease</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">SpideyBoy</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">SuperSimple</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">AshKetchup</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">PidgeonPower</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Spatula</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">CallieX</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">CoolPlay</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">LottaHair</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Notte</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Vivy</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">person50605</td>
                <td colspan="10"></td><td class="total">0</td></tr></table></div></div>
    <div id="bottomtext"><span class="menu"><a href="index.html">Overview</a> - </span><span class="menu"><a href="../about_ccsdt.html">Details</a> - </span><span class="menu"><a href="standings.html">Standings</a></span><span class="menuspacer"></span><span class="menu"><a href="1.html">Week 1</a> - </span><span class="menu"><a href="2.html">Week 2</a> - </span><span class="menu"><a href="3.html">Week 3</a> - </span><span class="menu">Week 4 - </span><span class="menu"><a href="5.html">Week 5</a> - </span><span id="updated"><span class="label">Updates every 10 mins. Last Update: </span>2025-10-05 23:52 UTC</span></div>